
#pragma once

#include <WinSock2.h>
#include <WS2tcpip.h>

#pragma comment(lib, "ws2_32")

#if defined(DEBUG) | defined(_DEBUG)
#pragma comment(lib, "ZEROLowLib.lib")
#else
#pragma comment(lib, "ZEROLowLib")
#endif

#define		PORT		4551
#define		PACKET_SIZE		1024
#define		SERVER_IP	"127.0.0.1"

#define		ID_SIZE		64
#define		PASS_SIZE	64

enum PACKET_HEADER
{
	PP_NONE,
	PP_CONNECT,
	PP_GAMEENTER,
	PP_DISCONNECT,
	PP_LOGIN,
	PP_LOGIN_FAILED,
	PP_LOGIN_SUCC,
	PP_USER_LOGIN,
	PP_USER_ALLREADY,
	PP_PLAYER_GAMESTART,
	PP_CHARACTER_INIT,
	PP_CHARACTER_INIT_SUCC,
	PP_CHARACTER_MOVE,
	PP_CHARACTER_MOVE_SUCC,
	PP_OTHERPLAYER_MOVE,
	PP_CHARACTER_DISCONNECT,
	PP_OTHERPLAYER_DISCONNNECT,
	PP_CHARACTER_ROTATION,
	PP_CHARACTER_ROTATION_SUCC,
	PP_OTHERPLAYER_ROTATION,
	PP_PLAYER_ANIMSTATE,
	PP_OTHERPLAYER_ANIMSTATE,
	PP_JUMP_PLAYER,
	PP_OTHERPLAYER_JUMP,
	PP_BOX_CREATE,
	PP_TIME_START,
	PP_PLAYER_SHOOT,
	PP_OTHERPLAYER_SHOOT,
	PP_LEFTCAR_MOVE,
	PP_RIGHTCAR_MOVE,
	PP_PLAYER_HEAT,
	PP_OTHERPLAYER_HEAT
};

enum MOVE_PLAYER
{
	MP_NONE,
	MP_LEFT,
	MP_RIGHT,
	MP_FRONT,
	MP_BACK
};

enum SERIAL_OBJECT_TYPE
{
	SOT_USER
};

typedef struct _tagPacket
{
	int							iTotalSize;
	int							iNumber;
	PACKET_HEADER	eHeader;
	char	strPacket[PACKET_SIZE];
}PACKET, *PPACKET;
